In [2]:
import csv
import numpy as np

In [3]:
file = open("data/FisherIris_ML.csv")
iris = np.loadtxt(file, delimiter=",")

print(iris)

[[  2.  14.  33.  50.   0.]
 [ 24.  56.  31.  67.   1.]
 [ 23.  51.  31.  69.   1.]
 [  2.  10.  36.  46.   0.]
 [ 20.  52.  30.  65.   1.]
 [ 19.  51.  27.  58.   1.]
 [ 13.  45.  28.  57.   2.]
 [ 16.  47.  33.  63.   2.]
 [ 17.  45.  25.  49.   1.]
 [ 14.  47.  32.  70.   2.]
 [  2.  16.  31.  48. -10.]
 [ 19.  50.  25.  63.   1.]
 [  1.  14.  36.  49.   0.]
 [  2.  13.  32.  44.   0.]
 [ 12.  40.  26.  58.   2.]
 [ 18.  49.  27.  63.   1.]
 [ 10.  33.  23.  50.   2.]
 [  2.  16.  38.  51.   0.]
 [  2.  16.  30.  50.   0.]
 [ 21.  56.  28.  64.   1.]
 [  4.  19.  38.  51.   0.]
 [  2.  14.  30.  49.   0.]
 [ 10.  41.  27.  58.   2.]
 [ 15.  45.  29.  60. -12.]
 [  2.  14.  36.  50.   0.]
 [ 19.  51.  27.  58.   1.]
 [  4.  15.  34.  54.   0.]
 [ 18.  55.  31.  64.   1.]
 [ 10.  33.  24.  49.   2.]
 [  2.  14.  42.  55.   0.]
 [ 15.  50.  22.  60.   1.]
 [ 14.  39.  27.  52.   2.]
 [  2.  14.  29.  44.   0.]
 [ 12.  39.  27.  58.   2.]
 [ 23.  57.  32.  69.   1.]
 [ 15.  42.  30.  59